"""Public M1 through M4 contracts for the network topology agent."""

from .config import load_app_config, load_device_mapping
from .image import (
    ImageBundle,
    ImageView,
    load_image_bundle,
    original_bbox_to_view,
    original_polyline_to_view,
    original_point_to_view,
    scale_original_point,
    view_bbox_to_original,
    view_polyline_to_original,
    view_point_to_original,
)
from .llm import (
    ModelCallResult,
    ModelHttpAttempt,
    ModelImage,
    ModelUsage,
    OpenAICompatibleModelClient,
    RawModelResult,
    SkillName,
)
from .models import (
    ConfigurationError,
    InputError,
    ModelInvocationError,
    PayloadValidationError,
    PlatformResourceError,
    PlatformSubmissionError,
    PlatformTopologyPayload,
    ResolvedTopologyIR,
    SubmissionResult,
    SubmissionUncertainError,
    TaskInput,
    TopologyAgentError,
    TopologyIR,
    TopologyObservation,
    TopologyUnresolvedError,
    ValidationReport,
)
from .recognition import RecognitionStatistics, recognize_topology

__version__ = "0.1.0"

__all__ = [
    "ConfigurationError",
    "ImageBundle",
    "ImageView",
    "InputError",
    "ModelInvocationError",
    "ModelCallResult",
    "ModelHttpAttempt",
    "ModelImage",
    "ModelUsage",
    "OpenAICompatibleModelClient",
    "PayloadValidationError",
    "PlatformResourceError",
    "PlatformSubmissionError",
    "PlatformTopologyPayload",
    "ResolvedTopologyIR",
    "RawModelResult",
    "RecognitionStatistics",
    "SkillName",
    "SubmissionResult",
    "SubmissionUncertainError",
    "TaskInput",
    "TopologyAgentError",
    "TopologyIR",
    "TopologyObservation",
    "TopologyUnresolvedError",
    "ValidationReport",
    "load_app_config",
    "load_device_mapping",
    "load_image_bundle",
    "original_bbox_to_view",
    "original_polyline_to_view",
    "original_point_to_view",
    "recognize_topology",
    "scale_original_point",
    "view_bbox_to_original",
    "view_polyline_to_original",
    "view_point_to_original",
]
